### ISSUE TITLE
Missing Graph DB / Results DB setup

### ISSUE THREAD

**Issue by Zest-nikunj** [OpenCSPM/opencspm-terraform-gcp#1]
@bgeesaman This terraform module seem to be missing the graph DB/result DB setup. Also, there is no detail about GUI setup in here. Appreciate any pointers in that direction.

**Comment by bgeesaman** [comment]
Hi @Zest-nikunj The module includes this cloud-init script https://github.com/OpenCSPM/opencspm-terraform-gcp/blob/main/collection/gcp/assets/cloud-config.yaml which clones and runs from the OpenCSPM repo on the VM defined here: https://github.com/OpenCSPM/opencspm-terraform-gcp/blob/main/collection/gcp/vm.tf

**Comment by Zest-nikunj** [comment]
Thanks @bgeesaman, I was looking for standalone PostgreSQL and Redis setup. But I do understand the setup. Thanks again.
